# Generated by Django 3.2.3 on 2021-07-06 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0004_auto_20210706_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(through='rooms.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
