# Generated by Django 3.2.3 on 2021-06-18 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(10)], verbose_name='weight'),
        ),
    ]
